### ISSUE TITLE
Error: Manifest for floydhub/dl-docker:gpu not found

### ISSUE THREAD

**Issue by petecog** [floydhub/dl-docker#52]
Hi - looks like the perfect docker build!

I followed your steps, but after the build, when I came to run it:
`$ nvidia-docker run -it -p 8888:8888 -p 6006:6006 -v /media/data1:/root/sharedfolder floydhub/dl-docker:gpu bash
`
I got
`
nvidia-docker | 2017/04/12 11:35:25 Error: Error response from daemon: manifest for floydhub/dl-docker:gpu not found
`

I'm not sure if this is a docker / nvidia-docker / your build issue. But any steer you might have very much welcomed!

I notice that floydhub/dl-docker is not appearing as a repository when I run `nvidia-docker images`, but there is 'something' there, following the build. Rep and Tag = `<none>` 

`REPOSITORY                TAG                            IMAGE ID            CREATED              SIZE`

`<none>                    <none>                         9970b532e83a        55 minutes ago       10.5 GB
nvidia/cuda               8.0-cudnn5-devel-ubuntu14.04   2b185ca91cd9        11 days ago          1.79 GB
`

Could the build have failed to 'register' the repository in some way?

**Comment by petecog** [comment]
Cancle my last! on a re-build it seems to work. Great set up. Many thanks.

One suggestion - PyMC3 would be a great addition, but there is already a lot going on in there!

**Comment by tarvos21** [comment]
Hi, @petecog, how do you solve this? I encounter the same error with you? What do you mean by "re-built"?
Thanks!

**Comment by hayday100** [comment]
@tarvos21 It won't just resolve by rerun the docker build command.  There is a missing flag for cmake in Dockerfile you need to add.  Please refer to [https://github.com/floydhub/dl-docker/issues/50](url)

**Comment by sbatururimi** [comment]
@hayday100 The issue seems closed and wrong link. Could you specify what flag to put and where, please?

@petecog Could you help with that, please?

**Comment by petecog** [comment]
hi @saiprashanths - you message got through.

Happy to close the issue. I've not been using the build since about May 17, so my memory is sketchy. I think I just removed the docker image and rebuilt from scratch and it worked.

If I recall, I stopped trying to use dockerised python because I couldn't work out a way of getting it to write to shared volumes as anything other than root.

**Comment by sbatururimi** [comment]
@petecog I think it was me(about the message). 
Could you maybe recommend a way/image you prefer to use when working with Deep Learning on Docker if any?
